### ISSUE TITLE
Optimum solution

### ISSUE THREAD

**Issue by dreinon** [tpaviot/ProcessScheduler#62]
I think an optimum solution stop criteria was implemented, but in my experience, until solver doesn't finish max_time, it doesn't stop even though optimal solution is found (in case of resource_utilization, optimal solution is 100). Are there tests of this feature?

Thanks.

**Comment by tpaviot** [comment]
Right now, the criterion to determine that an optimum ``opt`` is found for an objective ``obj`` is the problem is unsatisfiable when adding the constraint ``obj < opt``. I remember you told me that setting a maximum of 100 for resource utilization results in a higher computation time, so I did not add it. I will create a branch with the related commit so that you can test.

**Comment by tpaviot** [comment]
See branch max-utilization and commit bc2573649fc0bb4e7a9e994473f0da552cc30421

**Comment by dreinon** [comment]
Solved by #70
