### ISSUE TITLE
Adding Constraint Class to base for type hints

### ISSUE THREAD

**Issue by dreinon** [tpaviot/ProcessScheduler#97]
I would like to specify with type hints if I return a ProcessScheduler constraint but I do not have access to Constraint class.

**Comment by tpaviot** [comment]
All constraints inherit from the ``_Constraint`` base class (https://github.com/tpaviot/ProcessScheduler/blob/master/processscheduler/base.py#L90).

I'm thinking about introducing a richer class hierarchy, that would be easier for the solver to adopt specific strategies.

Another thing to know, I faced many circular references issues while trying to run mypy on ProcessScheduler. Indeed, in order to get mypy properly executed, each module must imports all types.

**Comment by tpaviot** [comment]
To avoid circular references in type hints, I suggest following PEP 484

https://www.python.org/dev/peps/pep-0484/#forward-references

Thus the type hint could look like this:
```python
def my_method(self, a_constraint: 'Constraint') -> None:
```

**Comment by dreinon** [comment]
Have you read this already?

[https://www.python.org/dev/peps/pep-0563/](https://www.python.org/dev/peps/pep-0563/)

**Comment by tpaviot** [comment]
No.

**Comment by dreinon** [comment]
Basically, importing the following can make forward references work out:
```python
from __future__ import annotations
```
Although strings are totally duable.
Closing the issue :smile:
